source 'https://github.com/CocoaPods/Specs'

platform :tvos, ‘9.0’
use_frameworks!

target ‘eSports’ do
    pod 'Alamofire', '~> 3.4'
    pod 'AlamofireImage', '~> 2.0'
    pod 'SwiftyJSON'
    pod 'Ji', '~> 1.2.0'
end