source 'https://github.com/CocoaPods/Specs'

platform :ios, '8.0'
use_frameworks!

target ‘eSports’ do
    pod 'Alamofire'
    pod 'AlamofireImage', '~> 2.0'
    pod 'SwiftyJSON'
    pod 'DZNEmptyDataSet'
    pod 'Ji', '~> 1.2.0'
end